In [91]:
import random 
import torch 
import torch.optim as optim
from torch_geometric.nn.models import LightGCN 
from sqlalchemy import create_engine
import pandas as pd
import joblib 


In [92]:
DB_URL = "mysql+pymysql://root:123456@127.0.0.1:3306/onlineshop"
engine = create_engine(DB_URL)

In [93]:
df = pd.read_sql(
    """
    SELECT user_id, product_id, interaction_type
    FROM user_product_interactions
    WHERE user_id IN (
        SELECT id FROM users WHERE name LIKE '%%syn%%'
    )
    """,
    engine
)

In [94]:
df.tail()

,user_id,product_id,interaction_type
10014,984,168,cart_add
10015,984,157,R5
10016,984,175,cart_add
10017,984,172,wishlist_add
10018,984,159,R5


In [95]:
user_product_interactions = df[['user_id', 'product_id']].drop_duplicates()
user_product_interactions["user_idx"] = user_product_interactions["user_id"].astype("category").cat.codes 
user_product_interactions["product_idx"] = user_product_interactions["product_id"].astype("category").cat.codes

In [96]:
user_product_interactions.head()

,user_id,product_id,user_idx,product_idx
0,485,258,0,220
1,485,191,0,175
2,485,192,0,176
3,485,201,0,184
4,485,187,0,171


In [97]:
interactions = user_product_interactions[["user_idx", "product_idx"]].to_numpy()

In [98]:
num_users = user_product_interactions["user_idx"].nunique()
num_items = user_product_interactions["product_idx"].nunique()
num_nodes = num_users + num_items

In [99]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [100]:
edge_list = []
for user_idx,item_idx in interactions: 
    edge_list.append((user_idx, num_users + item_idx))
    edge_list.append((num_users + item_idx, user_idx))


In [101]:
edge_list

[(np.int16(0), np.int16(720)),
 (np.int16(720), np.int16(0)),
 (np.int16(0), np.int16(675)),
 (np.int16(675), np.int16(0)),
 (np.int16(0), np.int16(676)),
 (np.int16(676), np.int16(0)),
 (np.int16(0), np.int16(684)),
 (np.int16(684), np.int16(0)),
 (np.int16(0), np.int16(671)),
 (np.int16(671), np.int16(0)),
 (np.int16(0), np.int16(693)),
 (np.int16(693), np.int16(0)),
 (np.int16(0), np.int16(725)),
 (np.int16(725), np.int16(0)),
 (np.int16(0), np.int16(686)),
 (np.int16(686), np.int16(0)),
 (np.int16(0), np.int16(551)),
 (np.int16(551), np.int16(0)),
 (np.int16(0), np.int16(719)),
 (np.int16(719), np.int16(0)),
 (np.int16(0), np.int16(685)),
 (np.int16(685), np.int16(0)),
 (np.int16(0), np.int16(718)),
 (np.int16(718), np.int16(0)),
 (np.int16(0), np.int16(575)),
 (np.int16(575), np.int16(0)),
 (np.int16(0), np.int16(715)),
 (np.int16(715), np.int16(0)),
 (np.int16(0), np.int16(670)),
 (np.int16(670), np.int16(0)),
 (np.int16(0), np.int16(721)),
 (np.int16(721), np.int16(0)),
 (np.int

In [102]:
edge_index = torch.tensor(edge_list,dtype=torch.long)

In [103]:
edge_index

tensor([[  0, 720],
        [720,   0],
        [  0, 675],
        ...,
        [652, 499],
        [499, 656],
        [656, 499]])

In [104]:
edge_index =edge_index.t().contiguous().to(device)

In [105]:
edge_index

tensor([[  0, 720,   0,  ..., 652, 499, 656],
        [720,   0, 675,  ..., 499, 656, 499]])

In [106]:
user_pos_items = {user_idx:set() for user_idx in range(num_users)}
for user_idx,item_idx in interactions: 
    user_pos_items[user_idx].add(item_idx)

In [107]:
user_pos_items

{0: {np.int16(51),
  np.int16(75),
  np.int16(170),
  np.int16(171),
  np.int16(175),
  np.int16(176),
  np.int16(184),
  np.int16(185),
  np.int16(186),
  np.int16(193),
  np.int16(215),
  np.int16(218),
  np.int16(219),
  np.int16(220),
  np.int16(221),
  np.int16(225)},
 1: {np.int16(34),
  np.int16(39),
  np.int16(43),
  np.int16(59),
  np.int16(67),
  np.int16(104),
  np.int16(171),
  np.int16(173),
  np.int16(174),
  np.int16(175),
  np.int16(176),
  np.int16(193),
  np.int16(194),
  np.int16(195),
  np.int16(196),
  np.int16(197),
  np.int16(219),
  np.int16(221)},
 2: {np.int16(34),
  np.int16(37),
  np.int16(39),
  np.int16(171),
  np.int16(174),
  np.int16(175),
  np.int16(176),
  np.int16(177),
  np.int16(185),
  np.int16(186),
  np.int16(193),
  np.int16(195),
  np.int16(196),
  np.int16(197),
  np.int16(198),
  np.int16(199),
  np.int16(218),
  np.int16(238)},
 3: {np.int16(7),
  np.int16(37),
  np.int16(43),
  np.int16(68),
  np.int16(81),
  np.int16(170),
  np.int16(173)

In [108]:
def sample_batch(batch_size):
    users =[]
    pos_items = []
    neg_items = []
    for _ in range(batch_size):
        user_idx = random.randint(0,num_users-1)
        pos_item_idx = random.choice(list(user_pos_items[user_idx]))
        while True:
            neg_item_idx = random.randint(0,num_items-1)
            if neg_item_idx not in user_pos_items[user_idx]:
                break
        users.append(user_idx)
        pos_items.append(pos_item_idx)
        neg_items.append(neg_item_idx)
    users = torch.tensor(users,dtype=torch.long).to(device)
    pos_items = torch.tensor(pos_items,dtype=torch.long).to(device)
    neg_items = torch.tensor(neg_items,dtype=torch.long).to(device)
    return users,pos_items,neg_items

In [109]:
sample_batch(4)

(tensor([ 89,  45, 370, 370]),
 tensor([ 50, 172, 128,  18]),
 tensor([232, 226, 213, 100]))

In [110]:
embedding_dim = 64
num_layers = 3
batch_size = 30
epochs = 500
lr = 0.01

In [111]:
model = LightGCN(num_nodes, embedding_dim, num_layers).to(device)
optimizer = optim.Adam(model.parameters(), lr=lr)


In [112]:
model.embedding.weight

Parameter containing:
tensor([[ 0.0502,  0.0473, -0.0546,  ..., -0.0131,  0.0041,  0.0708],
        [-0.0022,  0.0610,  0.0729,  ..., -0.0539, -0.0174, -0.0345],
        [ 0.0672, -0.0110, -0.0799,  ...,  0.0150,  0.0635, -0.0758],
        ...,
        [ 0.0586, -0.0233,  0.0253,  ...,  0.0496, -0.0455, -0.0337],
        [-0.0208, -0.0128, -0.0035,  ...,  0.0261, -0.0390, -0.0238],
        [ 0.0425,  0.0812, -0.0033,  ..., -0.0391, -0.0519,  0.0368]],
       requires_grad=True)

In [113]:
model.train()
for epoch in range(epochs):
    users,pos_items,neg_items = sample_batch(batch_size)
    pos_item_nodes = num_users + pos_items
    neg_item_nodes = num_users + neg_items
    #Forward propagation
    final_embeddings = model.get_embedding(edge_index) 

    #BPR loss
    user_emb = final_embeddings[users]
    pos_item_emb = final_embeddings[pos_item_nodes]
    neg_item_emb = final_embeddings[neg_item_nodes]
    pos_scores = torch.sum(user_emb * pos_item_emb, dim=1) # Dot product between user and positive item embeddings
    neg_scores = torch.sum(user_emb * neg_item_emb, dim=1) # Dot product between user and negative item embeddings
    loss = model.recommendation_loss(pos_scores, neg_scores,node_id=users) 

    # Reset gradients
    optimizer.zero_grad()

    # Backpropagation
    loss.backward()
    # Update parameters
    optimizer.step()
    if (epoch + 1) % 10 == 0:
        print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}")



Epoch [10/500], Loss: 0.6172
Epoch [20/500], Loss: 0.4380
Epoch [30/500], Loss: 0.2635
Epoch [40/500], Loss: 0.1902
Epoch [50/500], Loss: 0.1505
Epoch [60/500], Loss: 0.1420
Epoch [70/500], Loss: 0.2372
Epoch [80/500], Loss: 0.1277
Epoch [90/500], Loss: 0.1878
Epoch [100/500], Loss: 0.1764
Epoch [110/500], Loss: 0.0921
Epoch [120/500], Loss: 0.3182
Epoch [130/500], Loss: 0.1113
Epoch [140/500], Loss: 0.2835
Epoch [150/500], Loss: 0.0548
Epoch [160/500], Loss: 0.2344
Epoch [170/500], Loss: 0.1229
Epoch [180/500], Loss: 0.3357
Epoch [190/500], Loss: 0.3903
Epoch [200/500], Loss: 0.0724
Epoch [210/500], Loss: 0.1165
Epoch [220/500], Loss: 0.1268
Epoch [230/500], Loss: 0.1454
Epoch [240/500], Loss: 0.1248
Epoch [250/500], Loss: 0.1139
Epoch [260/500], Loss: 0.0741
Epoch [270/500], Loss: 0.0535
Epoch [280/500], Loss: 0.2531
Epoch [290/500], Loss: 0.0245
Epoch [300/500], Loss: 0.1710
Epoch [310/500], Loss: 0.2680
Epoch [320/500], Loss: 0.0634
Epoch [330/500], Loss: 0.0743
Epoch [340/500], Lo

In [114]:
@torch.no_grad()
def recommend(user_idx, top_k=10):
    model.eval()
    user_tensor = torch.tensor([user_idx], dtype=torch.long).to(device)
    item_tensor = torch.arange(num_users, num_users + num_items, dtype=torch.long).to(device)
    indices = model.recommend(edge_index=edge_index, src_index=user_tensor, dst_index=item_tensor, k=top_k+100)
    indices = indices[0].tolist()
    recommended_items = [] 
    for idx in indices:
        item_idx = idx-num_users
        if item_idx not in user_pos_items[user_idx]:
            recommended_items.append(item_idx)
        if len(recommended_items) >= top_k:
            break
    return recommended_items

In [115]:
print("\nRecommend for user 0:")
print(recommend(user_idx=0, top_k=10))

print("\nRecommend for user 1:")
print(recommend(user_idx=1, top_k=10))


Recommend for user 0:
[195, 194, 177, 173, 174, 187, 37, 197, 39, 196]

Recommend for user 1:
[185, 220, 177, 170, 187, 37, 184, 218, 186, 172]


In [116]:
model.get_embedding(edge_index)

tensor([[-0.2061, -0.1136, -0.2301,  ...,  0.0464,  0.1865,  0.2450],
        [-0.2093, -0.1034, -0.1153,  ...,  0.0901,  0.0763,  0.4208],
        [-0.2607, -0.0112, -0.2114,  ...,  0.0804,  0.1238,  0.2658],
        ...,
        [ 0.1702,  0.4975,  0.4901,  ...,  0.5655, -0.5499,  0.5142],
        [ 0.0061,  0.3338,  0.2816,  ...,  0.5381, -0.3236,  0.4275],
        [ 0.1879,  0.3338,  0.4106,  ...,  0.4839, -0.4537,  0.5360]],
       grad_fn=<AddBackward0>)

In [117]:
def get_mapping(df): 
    product_idx_to_id = dict(zip(df["product_idx"], df["product_id"]))
    product_id_to_idx = dict(zip(df["product_id"], df["product_idx"]))
    user_id_to_idx = dict(zip(df["user_id"], df["user_idx"]))
    user_idx_to_id = dict(zip(df["user_idx"], df["user_id"]))
    return product_idx_to_id, product_id_to_idx, user_id_to_idx, user_idx_to_id

In [118]:
product_idx_to_id_mapping, product_id_to_idx_mapping, user_id_to_idx_mapping, user_idx_to_id_mapping = get_mapping(user_product_interactions)


In [119]:
item_embeddings = model.get_embedding(edge_index)[num_users:].detach().numpy()
user_embeddings = model.get_embedding(edge_index)[:num_users].detach().numpy()

In [120]:

joblib.dump(user_id_to_idx_mapping, "../models/lightgcn/user_id_to_idx_mapping.joblib")
joblib.dump(user_idx_to_id_mapping, "../models/lightgcn/user_idx_to_id_mapping.joblib")
joblib.dump(product_id_to_idx_mapping, "../models/lightgcn/product_id_to_idx_mapping.joblib")
joblib.dump(product_idx_to_id_mapping, "../models/lightgcn/product_idx_to_id_mapping.joblib")
joblib.dump(item_embeddings, "../models/lightgcn/item_embeddings.joblib")
joblib.dump(user_embeddings, "../models/lightgcn/user_embeddings.joblib")

['../models/lightgcn/user_embeddings.joblib']

## Testing

In [121]:
item_embeddings.shape

(243, 64)

In [122]:
item_embeddings[0]

array([ 0.13050395, -0.549837  ,  0.22419351,  0.3295257 , -0.28283936,
       -0.28424472,  0.01060197,  0.1648686 ,  0.08527207,  0.31189424,
       -0.3672882 ,  0.21091616,  0.09986399,  0.41686094,  0.15290031,
       -0.07549851,  0.17454006,  0.4703005 , -0.4146911 , -0.28520384,
       -0.38442427,  0.31629306, -0.26594758,  0.385284  , -0.4282929 ,
        0.13111487, -0.28354022,  0.36454412,  0.29190195, -0.02054996,
        0.40785235,  0.48268518, -0.04926452, -0.2975405 , -0.2951609 ,
       -0.34648147, -0.11835416,  0.45167685,  0.5048735 ,  0.4263629 ,
        0.04022864,  0.2651419 , -0.49229455, -0.29738703,  0.3303639 ,
        0.38263294, -0.38829574,  0.4499499 ,  0.24859092,  0.06977464,
       -0.13992366, -0.29302794, -0.39809772, -0.54000837,  0.41557145,
       -0.32812113,  0.3012358 ,  0.33422247,  0.2307021 ,  0.47982973,
        0.18460056, -0.49572837, -0.18125145, -0.34028947], dtype=float32)

In [123]:
item_embeddings.shape

(243, 64)

In [124]:
user_product_interactions.head()

,user_id,product_id,user_idx,product_idx
0,485,258,0,220
1,485,191,0,175
2,485,192,0,176
3,485,201,0,184
4,485,187,0,171


In [125]:
user_product_interactions[user_product_interactions["product_idx"] == 0]

,user_id,product_id,user_idx,product_idx
1385,554,5,69,0
9609,965,5,480,0
9671,968,5,483,0
9694,969,5,484,0
9730,971,5,486,0
9752,972,5,487,0
9805,974,5,489,0
9867,977,5,492,0
9888,978,5,493,0
9904,979,5,494,0


In [126]:
idx = product_id_to_idx_mapping.get(5)


In [127]:
from pydantic import  BaseModel
class Interaction(BaseModel): 
    product_id:int
    interaction_type:str

In [128]:
interactions = [Interaction(product_id=1, interaction_type="click"),
                Interaction(product_id=2, interaction_type="click"),
                Interaction(product_id=3, interaction_type="click"),
                Interaction(product_id=4, interaction_type="click"),
                Interaction(product_id=5, interaction_type="click")]


In [129]:
interactions_df = pd.DataFrame([{"product_id": i.product_id} for i in interactions])


In [130]:
from sklearn.model_selection import train_test_split
train,test = train_test_split(interactions, test_size=0.4, random_state=42)

In [131]:
train

[Interaction(product_id=3, interaction_type='click'),
 Interaction(product_id=1, interaction_type='click'),
 Interaction(product_id=4, interaction_type='click')]

In [132]:
test

[Interaction(product_id=2, interaction_type='click'),
 Interaction(product_id=5, interaction_type='click')]

In [133]:
type(interactions)

list

In [134]:
copy = df[df["product_id"] == 7].tail()

In [135]:
copy

,user_id,product_id,interaction_type
8271,898,7,wishlist_add
8285,899,7,R4
8568,913,7,wishlist_add
8838,926,7,click
8843,927,7,wishlist_add


In [136]:
copy.rename(columns={"user_id": "User id", "product_id":"Product id","interaction_type": "Interaction"}, inplace=True)

In [137]:
copy

,User id,Product id,Interaction
8271,898,7,wishlist_add
8285,899,7,R4
8568,913,7,wishlist_add
8838,926,7,click
8843,927,7,wishlist_add


In [138]:
copy["Interaction"] = copy["Interaction"].replace({"wishlist_add": "Add to Wishlist","R5": "Rating 5"}) 

In [139]:
copy

,User id,Product id,Interaction
8271,898,7,Add to Wishlist
8285,899,7,R4
8568,913,7,Add to Wishlist
8838,926,7,click
8843,927,7,Add to Wishlist


In [140]:
test_user_emb = torch.tensor(user_emb[0])

/var/folders/v1/f1gz50591kl2_tm8_gxbrtcc0000gn/T/ipykernel_66020/3020799642.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_user_emb = torch.tensor(user_emb[0])


In [141]:
test_user_emb

tensor([-0.2343,  0.1216, -0.1264, -0.0929, -0.3247,  0.1991, -0.4762,  0.2698,
         0.0226, -0.3509,  0.1643,  0.2608, -0.3415, -0.4642,  0.2037,  0.5286,
        -0.1507,  0.3898, -0.2048, -0.0260,  0.1364, -0.1656, -0.1635,  0.2408,
         0.2423,  0.2870, -0.1204,  0.3498,  0.1551,  0.6459,  0.0630,  0.1155,
         0.3155,  0.2714,  0.1862,  0.0457,  0.0999,  0.0457, -0.2913, -0.5092,
        -0.0909, -0.0430,  0.4012,  0.4446,  0.0909, -0.2204,  0.3447,  0.1882,
        -0.0235,  0.2950,  0.2603, -0.0648, -0.1001, -0.2253, -0.3617,  0.0660,
        -0.2271,  0.3335,  0.0991, -0.2145, -0.1549, -0.0300,  0.0358, -0.1778])

In [142]:
test_item_emb = torch.tensor(item_embeddings[0])

In [143]:
test_item_emb.shape

torch.Size([64])

In [144]:
test_user_emb.shape

torch.Size([64])

In [145]:
test_item_emb * test_user_emb

tensor([-0.0306, -0.0669, -0.0283, -0.0306,  0.0918, -0.0566, -0.0050,  0.0445,
         0.0019, -0.1094, -0.0604,  0.0550, -0.0341, -0.1935,  0.0311, -0.0399,
        -0.0263,  0.1833,  0.0849,  0.0074, -0.0524, -0.0524,  0.0435,  0.0928,
        -0.1038,  0.0376,  0.0341,  0.1275,  0.0453, -0.0133,  0.0257,  0.0558,
        -0.0155, -0.0807, -0.0550, -0.0158, -0.0118,  0.0206, -0.1471, -0.2171,
        -0.0037, -0.0114, -0.1975, -0.1322,  0.0300, -0.0843, -0.1339,  0.0847,
        -0.0058,  0.0206, -0.0364,  0.0190,  0.0399,  0.1217, -0.1503, -0.0217,
        -0.0684,  0.1115,  0.0229, -0.1029, -0.0286,  0.0149, -0.0065,  0.0605])

In [146]:
torch.sum(test_item_emb * test_user_emb, dim=0)

tensor(-0.9219)

In [147]:
# Export df to csv file 
df.to_csv('user_item_interactions.csv', index=False)

In [155]:
user_id_to_idx_mapping[487], product_id_to_idx_mapping[6], product_idx_to_id_mapping[1]

(2, 1, 6)