## Setup

In [161]:
import math 
import random 
import numpy as np 
import pandas as pd 
import torch
import torch.nn as nn
from torch.utils.data import Dataset,DataLoader
from sqlalchemy import create_engine


## Fetch data from database

In [162]:
DB_URL = "mysql+pymysql://root:123456@127.0.0.1:3306/onlineshop"
engine = create_engine(DB_URL)

In [163]:
df = pd.read_sql(
    """
    SELECT user_id, product_id, created_at
    FROM user_product_interactions
    WHERE user_id IN (
        SELECT id FROM users WHERE name LIKE '%%syn%%'
    )
    """,
    engine
)
num_items = pd.read_sql("SELECT COUNT(*) AS num_items FROM products", engine).iloc[0]['num_items']

In [164]:
df['created_at'] = pd.to_datetime(df['created_at'])

In [165]:
df.head()

,user_id,product_id,created_at
0,485,258,2026-04-17 18:15:13
1,485,191,2026-04-17 18:15:13
2,485,192,2026-04-17 18:15:13
3,485,201,2026-04-17 18:15:13
4,485,187,2026-04-17 18:15:13


In [166]:
interactions_df = df.rename(columns={'product_id':'item_id','created_at':'timestamp'}).sort_values(['user_id','timestamp']).reset_index(drop=True)

In [167]:
interactions_df.head()

,user_id,item_id,timestamp
0,485,258,2026-04-17 18:15:13
1,485,191,2026-04-17 18:15:13
2,485,192,2026-04-17 18:15:13
3,485,201,2026-04-17 18:15:13
4,485,187,2026-04-17 18:15:13


In [168]:
interactions_df.shape

(10019, 3)

## Mapping handling 

In [169]:
interactions_df["real_user_id"] = interactions_df["user_id"] 
interactions_df["user_id"] = interactions_df.groupby("user_id").ngroup() + 1 
interactions_df["real_item_id"] = interactions_df["item_id"]
interactions_df["item_id"] = interactions_df.groupby("item_id").ngroup() + 1

In [170]:
interactions_df.head()

,user_id,item_id,timestamp,real_user_id,real_item_id
0,1,221,2026-04-17 18:15:13,485,258
1,1,176,2026-04-17 18:15:13,485,191
2,1,177,2026-04-17 18:15:13,485,192
3,1,185,2026-04-17 18:15:13,485,201
4,1,172,2026-04-17 18:15:13,485,187


In [171]:
user_id_to_index = dict(zip(interactions_df["real_user_id"], interactions_df["user_id"])) 
item_id_to_index = dict(zip(interactions_df["real_item_id"], interactions_df["item_id"])) 
item_index_to_id = dict(zip(interactions_df["item_id"], interactions_df["real_item_id"])) 

In [172]:
user_id_to_index[485],item_id_to_index[191],item_index_to_id[221]

(1, 176, 258)

## I. CONSTANT VARIABLES FOR SETUP

In [173]:
SEED = 42 
MAX_SEQ_LEN = 30 
BATCH_SIZE = 64
PAD_ID = 0 
NUM_ITEMS = num_items
VOCAB_SIZE = NUM_ITEMS + 1

In [174]:
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

## Turn interactions into sequences


In [175]:
user_sequences = interactions_df.groupby("user_id")['item_id'].apply(list).to_dict()

In [176]:
user_sequences[1]

[221,
 176,
 177,
 185,
 172,
 194,
 221,
 226,
 187,
 52,
 220,
 186,
 219,
 76,
 187,
 220,
 216,
 171,
 222,
 176]

## Train test split 


In [177]:
train_user_sequences = {}
test_user_sequences = []
for user_id, seq in user_sequences.items():
    if len(seq) < 2 : continue
    train_sequence = seq[:-1]
    target_item = seq[-1]
    train_user_sequences[user_id] = train_sequence
    test_user_sequences.append({
        "user_id": user_id,
        "input_sequence": train_sequence,
        "target_item": target_item
    })


In [178]:
train_user_sequences[1]

[221,
 176,
 177,
 185,
 172,
 194,
 221,
 226,
 187,
 52,
 220,
 186,
 219,
 76,
 187,
 220,
 216,
 171,
 222]

## Create Training Samples FOR SASRec


In [179]:
training_samples = []

for user_id,seq in train_user_sequences.items():
    for target in range(1,len(seq)): 
        input_seq = seq[:target] 
        target_item = seq[target]

        if len(input_seq) > MAX_SEQ_LEN:
            input_seq = input_seq[-MAX_SEQ_LEN:]

        training_samples.append({
            "user_id":user_id,
            "input_sequence":input_seq,
            "target_item":target_item
        })
samples_df = pd.DataFrame(training_samples)

In [180]:
training_samples[1]

{'user_id': 1, 'input_sequence': [221, 176], 'target_item': 177}

In [181]:
samples_df.head()

,user_id,input_sequence,target_item
0,1,[221],176
1,1,"[221, 176]",177
2,1,"[221, 176, 177]",185
3,1,"[221, 176, 177, 185]",172
4,1,"[221, 176, 177, 185, 172]",194


## Create Custom Pytorch Dataset 

In [182]:
class SASRecDataset(Dataset):
    def __init__(self,samples,max_seq_len,pad_id = 0): 
        self.samples = samples
        self.max_seq_len = max_seq_len
        self.pad_id = pad_id
    def __len__(self):
        return len(self.samples)
    def __getitem__(self,idx):
        sample = self.samples[idx] 
        input_seq = sample["input_sequence"]
        target_item = sample["target_item"]

        padding_length = self.max_seq_len - len(input_seq)
        padded_sequence = [self.pad_id] * padding_length + input_seq

        input_tensor = torch.tensor(padded_sequence,dtype=torch.long)
        target_tensor = torch.tensor(target_item,dtype=torch.long)

        return input_tensor,target_tensor
train_dataset = SASRecDataset(training_samples,MAX_SEQ_LEN,PAD_ID)

In [183]:
input,target = train_dataset[0]
input,target

(tensor([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0, 221]),
 tensor(176))

## Create Dataloader

In [184]:
train_loader = DataLoader(train_dataset,batch_size=BATCH_SIZE,shuffle=True)

In [185]:
input_batch,target_batch = next(iter(train_loader))
print("Input batch shape:",input_batch.shape)
print("Target batch shape:",target_batch.shape)
print("Input first item in batch example:\n",input_batch[0])
print("Target first item in batch example:\n",target_batch[0])

Input batch shape: torch.Size([64, 30])
Target batch shape: torch.Size([64])
Input first item in batch example:
 tensor([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  38, 196,
        185, 188,  44, 222,  80, 220,  44, 195, 171, 195, 226, 178, 221, 186,
         21,  40])
Target first item in batch example:
 tensor(198)


## Create causal attention mask function 

In [186]:
def create_causal_mask(seq_len,device): 
    mask = torch. triu(
        torch.ones(seq_len,seq_len,device = device),
        diagonal = 1
    )
    mask = mask.masked_fill(mask==1,float("-inf"))
    mask = mask.masked_fill(mask==0,float(0.0))
    return mask

In [187]:
create_causal_mask(3,"cpu")

tensor([[0., -inf, -inf],
        [0., 0., -inf],
        [0., 0., 0.]])

## Create Class SASRecModel

In [188]:
class SASRecModel(nn.Module):
    def __init__(
        self,
        num_items,
        max_seq_len,
        embedding_dim=64,
        num_attention_heads=2,
        num_transformer_blocks=2,
        dropout_rate=0.1 , 
        pad_id = 0
    ):
        super().__init__()
        self.pad_id = pad_id
        self.num_items = num_items
        self.max_seq_len = max_seq_len
        self.embedding_dim = embedding_dim
        # 1. Item Embedding Layer
        self.item_embedding = nn.Embedding(
            num_embeddings = VOCAB_SIZE, 
            embedding_dim = embedding_dim, 
            padding_idx = 0 # Embedding for padding will be a zero vector and not updated during training
        )
        # 2. Position Embedding Layer
        self.position_embedding = nn.Embedding(
            num_embeddings = max_seq_len,
            embedding_dim = embedding_dim
        )

        self.dropout = nn.Dropout(dropout_rate) # Dropout layer for regularization

        # Transformer Blocks
        transformer_block = nn.TransformerEncoderLayer(
            # Multi-Head Self-Attention
            d_model = embedding_dim,  # Embedding dimension for the transformer, define the dim for matrices Q, K, V
            nhead = num_attention_heads, # Number of attention heads in the multi-head attention mechanism

            # Multi Layer Perceptron (MLP)
            dropout = dropout_rate, # Dropout rate for regularization
            dim_feedforward = embedding_dim * 4, # Expansion Weights 
            activation = "gelu", # Activation function for the feedforward network

            #Supplementary Arguments
            batch_first = True, # Input shape (batch_size, seq_len, embedding_dim)
            norm_first = True # Apply layer normalization before the attention and feedforward layers
        )
        # 3. Transformer Layer
        self.transformer_encoder = nn.TransformerEncoder(
            encoder_layer = transformer_block, # Base transformer block to be repeated
            num_layers = num_transformer_blocks # Number of transformer blocks
        )

        self.layer_norm = nn.LayerNorm(embedding_dim) # Layer normalization to stabilize training

        # 4. Output Layer
        self.output_layer = nn.Linear(
            embedding_dim, # Input dimension from the transformer output
            VOCAB_SIZE # Output dimension equal to vocabulary size
        )
    def forward(self,input_sequences):
        device = input_sequences.device
        batch_size,seq_len = input_sequences.size() 

        positions = torch.arange(seq_len,device=device)
        positions = positions.unsqueeze(0) 
        positions = positions.expand(batch_size,seq_len) 

        item_emb = self.item_embedding(input_sequences) 
        pos_emb = self.position_embedding(positions) 
        
        x = item_emb + pos_emb 
        x = self.dropout(x) 

        # Create causal mask for self-attention to prevent attending to future positions
        causal_mask = create_causal_mask(seq_len, device)

        # Create padding mask to ignore padded positions in the input sequences
        padding_mask_bool = input_sequences.eq(self.pad_id) #[batch_size,seq_len]
        padding_mask = torch.zeros(batch_size, seq_len, device=device, dtype=x.dtype) #[batch_size,seq_len]
        padding_mask = padding_mask.masked_fill(padding_mask_bool, float("-inf"))  #[batch_size,seq_len]

 
        for layer in self.transformer_encoder.layers:
            x = layer(
                x, 
                src_mask=causal_mask, #(seq_len, seq_len) mask for causal attention
                src_key_padding_mask=padding_mask #(batch_size, seq_len) mask for padding positions
            )
            x = torch.nan_to_num(x, nan=0.0)


        x = self.layer_norm(x) 

        # Extract the last hidden state corresponding to the last item in the sequence
        last_hidden_embeddings = x[:,-1,:] 

        # Using the last hidden state to predict the next item in the sequence
        logits = self.output_layer(last_hidden_embeddings) 

        return logits 


## II. CONSTANT VARIABLES FOR TRAINING

In [189]:
EMBEDDING_DIM = 256
NUM_ATTENTION_HEADS = 4
NUM_TRANSFORMER_BLOCKS = 4
DROPOUT_RATE = 0.2
NUM_EPOCHS = 100

## Initialize SASRec Model


In [190]:
model = SASRecModel(
    num_items = NUM_ITEMS, 
    max_seq_len = MAX_SEQ_LEN, 
    embedding_dim = EMBEDDING_DIM, 
    num_attention_heads = NUM_ATTENTION_HEADS, 
    num_transformer_blocks = NUM_TRANSFORMER_BLOCKS, 
    dropout_rate = DROPOUT_RATE 
)

/var/folders/v1/f1gz50591kl2_tm8_gxbrtcc0000gn/T/ipykernel_54874/3997828244.py:47: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  self.transformer_encoder = nn.TransformerEncoder(


## Testing Model with 1 batch

In [191]:
input_batch,target_batch = next(iter(train_loader))

In [192]:
input_batch,target_batch 

(tensor([[  0,   0,   0,  ...,   0,  83,  89],
         [  0,   0,   0,  ...,  77, 188, 221],
         [  0,   0,   0,  ...,  19,  29, 123],
         ...,
         [  0,   0,   0,  ..., 141, 123, 115],
         [  0,   0,   0,  ..., 134, 206, 168],
         [  0,   0,   0,  ...,  59, 206, 200]]),
 tensor([ 21,  87, 129, 224,  33, 217, 133, 111, 234, 188, 165, 223,  59,  60,
          65,  51,  61, 179, 188, 171, 229,  52,  11,  51,  27,  29,  50, 162,
         206,  56, 225,  68,  57, 122, 102,  47, 216,  30, 202, 117, 233,  48,
         138,  43,   5,  59, 186,  38, 197, 197,   6,   2, 199, 202,  30, 114,
          13, 170,  95, 204, 198, 128,  46, 194]))

In [193]:
input_batch.shape,target_batch.shape

(torch.Size([64, 30]), torch.Size([64]))

In [194]:
logits = model(input_batch)
print("Logits shape:",logits.shape)
print("Logits example:\n",logits)

Logits shape: torch.Size([64, 244])
Logits example:
 tensor([[-0.2598,  0.2407, -0.2760,  ...,  0.7679,  0.7323,  0.3073],
        [-0.0858,  0.2797, -0.5517,  ...,  0.7105,  0.0356, -0.0732],
        [-0.1595,  0.1486, -0.8667,  ...,  1.0547,  0.4350,  0.1520],
        ...,
        [-0.0232,  0.2797,  0.0344,  ...,  0.1517,  0.9740, -0.1581],
        [ 0.3802,  0.7546, -0.5785,  ...,  0.5099,  1.4334,  0.4550],
        [ 0.5935,  0.3525, -0.7102,  ...,  0.7911,  0.4636,  0.8063]],
       grad_fn=<AddmmBackward0>)


In [195]:
loss_function = nn.CrossEntropyLoss(ignore_index=0) 

# Logits shape: (batch_size, num_items+1), Target shape: (batch_size,)
loss = loss_function(logits,target_batch) 
print("Loss:",loss.item())

Loss: 5.777629375457764


## Create Training Loop for SASRec

In [196]:
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu") 
model = model.to(device)

In [197]:
loss_function = nn.CrossEntropyLoss(ignore_index=0)
optimizer = torch.optim.Adam(
    model.parameters(),
    lr = 0.001,
    weight_decay = 1e-6
)


In [198]:
for epoch in range(1,NUM_EPOCHS+1):
    model.train() 
    total_loss = 0.0 
    total_batches = 0 
    
    for input_batch,target_batch in train_loader:
        input_batch = input_batch.to(device)
        target_batch = target_batch.to(device) 
        # -------- Training Step --------
        # 1. Feed Forward
        logits = model(input_batch)

        # 2. Compute Loss
        loss = loss_function(logits,target_batch) 
        
        # 3. Reset gradients
        optimizer.zero_grad()

        # 4. Feed Backward
        loss.backward() 

        # 5. Update Parameters 
        optimizer.step()
        # -------- Training Step --------

        # Accumulate loss for monitoring 
        total_loss += loss.item()
        total_batches += 1
        
    avg_loss = total_loss / total_batches
    print(f"Epoch {epoch}/{NUM_EPOCHS}, Average Loss: {avg_loss:.4f}")

Epoch 1/100, Average Loss: 4.7151
Epoch 2/100, Average Loss: 4.0295
Epoch 3/100, Average Loss: 3.8875
Epoch 4/100, Average Loss: 3.8035
Epoch 5/100, Average Loss: 3.7141
Epoch 6/100, Average Loss: 3.6076
Epoch 7/100, Average Loss: 3.5027
Epoch 8/100, Average Loss: 3.3767
Epoch 9/100, Average Loss: 3.2513
Epoch 10/100, Average Loss: 3.1370
Epoch 11/100, Average Loss: 3.0024
Epoch 12/100, Average Loss: 2.8799
Epoch 13/100, Average Loss: 2.7117
Epoch 14/100, Average Loss: 2.5774
Epoch 15/100, Average Loss: 2.4486
Epoch 16/100, Average Loss: 2.3050
Epoch 17/100, Average Loss: 2.1469
Epoch 18/100, Average Loss: 2.0136
Epoch 19/100, Average Loss: 1.8679
Epoch 20/100, Average Loss: 1.7581
Epoch 21/100, Average Loss: 1.6232
Epoch 22/100, Average Loss: 1.5248
Epoch 23/100, Average Loss: 1.4232
Epoch 24/100, Average Loss: 1.3442
Epoch 25/100, Average Loss: 1.2597
Epoch 26/100, Average Loss: 1.1683
Epoch 27/100, Average Loss: 1.0928
Epoch 28/100, Average Loss: 1.0465
Epoch 29/100, Average Loss: 0

In [226]:
model.state_dict()

OrderedDict([('item_embedding.weight',
              tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
                      [-1.7795,  0.0642,  0.0860,  ...,  1.1958,  0.6133,  0.1600],
                      [ 1.5584,  0.0131, -0.8033,  ..., -0.3310, -0.9356, -0.6179],
                      ...,
                      [ 1.4869,  0.6814, -0.2091,  ..., -2.2190, -1.2260, -0.2538],
                      [-1.2911,  1.9992,  0.4574,  ..., -0.7450, -1.0046, -0.7227],
                      [-0.3827,  1.5944, -0.7970,  ..., -3.2430, -0.5140, -0.5547]])),
             ('position_embedding.weight',
              tensor([[-1.0003e-31,  9.4428e-32,  1.0142e-31,  ...,  1.0253e-31,
                        9.8931e-32, -1.0783e-31],
                      [ 1.0460e-31,  9.9900e-32,  9.4717e-32,  ...,  1.0345e-31,
                       -9.7955e-32, -9.9962e-32],
                      [-1.0135e-31, -1.0074e-31,  1.0369e-31,  ..., -1.0177e-31,
                        1.0016e-31,  9.72

## Saving Model

In [217]:
# Save model state_dict
torch.save({"model_state_dict": model.state_dict(),
            "pad_id": int(PAD_ID),
            "embedding_dim": int(EMBEDDING_DIM),
            "max_seq_len": int(MAX_SEQ_LEN),
            "num_items": int(NUM_ITEMS),
            "num_attention_heads": int(NUM_ATTENTION_HEADS),
            "num_transformer_blocks": int(NUM_TRANSFORMER_BLOCKS),
            "dropout_rate": float(DROPOUT_RATE),
            }, "../models/sasrec/sasrec_checkpoint.pth")  
# Save mappings
torch.save(user_id_to_index, "../models/sasrec/user_id_to_index.pth")
torch.save(item_id_to_index, "../models/sasrec/item_id_to_index.pth")
torch.save(item_index_to_id, "../models/sasrec/item_index_to_id.pth")


# ------------------ TESTING ------------------ 

## Recommend for next items  

In [218]:
TOP_K = 50

In [219]:
def recommend(model,user_sequence,top_k=10): 
    model.eval()
    if len(user_sequence) > MAX_SEQ_LEN: 
        user_sequence = user_sequence[-MAX_SEQ_LEN:] 
    padding_length = MAX_SEQ_LEN - len(user_sequence)
    padded_sequence = [0] * padding_length + user_sequence

    input_tensor = torch.tensor(
        [padded_sequence], 
        dtype = torch.long
    ).to(device) 

    with torch.no_grad():
        logits = model(input_tensor) 
        scores = logits[0] 
    
    scores[0] = float("-inf")

    for item_id in set(user_sequence): 
        scores[item_id] = float("-inf")
    top_scores,top_items = torch.topk(scores,k=top_k)

    return top_items.cpu().tolist(),top_scores.cpu().tolist()

In [220]:
index = item_id_to_index[188]
index

173

In [221]:
recommended_items = recommend(
    model=model,
    user_sequence=[index],
    top_k=10
) 

recommended_items

RuntimeError: Placeholder storage has not been allocated on MPS device!

In [222]:
recommended_items_id = [item_index_to_id[item_index] for item_index in recommended_items]
recommended_items_id

TypeError: cannot use 'list' as a dict key (unhashable type: 'list')

In [223]:
item_id_to_index[256]

219

In [224]:
logits

tensor([[-4.6058e+00, -1.7574e+00, -5.4354e+00, -4.9104e+00,  1.3899e+00,
          1.7582e+00,  1.7155e+00, -2.0509e+00, -2.4457e+00, -2.7326e+00,
         -3.5659e-01, -1.1363e+00,  2.5655e+00, -4.6306e-01,  3.3002e+00,
         -3.0935e+00, -4.6792e+00,  1.2013e+00, -1.6510e+00,  1.4341e-01,
         -1.4488e+00, -5.1950e+00,  4.1137e+00,  1.9024e-01,  1.0257e+00,
          3.0427e-01, -3.5684e+00, -1.9426e+00,  8.5323e-02,  1.2546e-01,
          1.5202e+00, -3.6988e-01, -1.9189e+00, -1.7962e+00,  9.6615e+00,
         -1.7375e+00, -3.4666e+00,  2.7675e+00, -2.9003e+00, -2.3948e-01,
         -6.2696e+00,  4.7363e+00,  6.1647e-01,  2.9192e+00, -9.3153e+00,
          1.3024e+00,  4.9805e-02,  2.5053e+00,  1.6795e+00,  1.4231e+00,
         -1.2195e+00,  3.1531e+00, -8.7048e-03,  4.1088e+00, -3.7159e-01,
         -9.0866e-02,  1.1639e+00, -2.8051e+00,  3.1199e+00,  1.3377e+00,
          4.6168e+00, -3.3881e+00, -2.9467e+00, -4.8531e-01, -5.4941e+00,
         -5.2388e+00, -4.0803e+00, -1.

## Evaluation

In [225]:
def evaluate_model(model,test_samples,top_k=10): 
    hits = []
    recalls = []
    ndcgs = []
    for sample in test_samples:
        user_sequence = sample["input_sequence"]
        target_item = sample["target_item"]
        recommended_items,recommended_scores = recommend(
            model=model,
            user_sequence=user_sequence,
            top_k=top_k
        )

        if target_item in recommended_items: 
            hit = 1
            recall = 1 
            rank = recommended_items.index(target_item) + 1 
            ndcg = 1/math.log2(rank+1) 
        else:
            hit = 0 
            recall = 0 
            ndcg = 0
        hits.append(hit)
        recalls.append(recall)
        ndcgs.append(ndcg)  
    hit_at_k = sum(hits)/len(hits)
    recall_at_k = sum(recalls)/len(recalls)
    ndcg_at_k = sum(ndcgs)/len(ndcgs)

    return hit_at_k, recall_at_k, ndcg_at_k, hits, recalls, ndcgs

In [ ]:
hit_at_10, recall_at_10, ndcg_at_10 ,hits, recalls, ndcgs = evaluate_model(model,test_user_sequences,top_k=10)
print(f"Hit@10: {hit_at_10:.4f}, Recall@10: {recall_at_10:.4f}, NDCG@10: {ndcg_at_10:.4f}") 

Hit@10: 0.2080, Recall@10: 0.2080, NDCG@10: 0.1080


In [ ]:
hits.count(1)

84

In [ ]:
len(test_user_sequences)

500

In [ ]:
len(train_user_sequences)

500

## PLAYAROUND

In [ ]:
model.state_dict()

OrderedDict([('item_embedding.weight',
              tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
                      [-1.7052,  0.2038,  0.0638,  ...,  1.4430,  0.6490,  0.2800],
                      [ 1.5394,  0.0817, -0.8138,  ..., -0.0685, -0.8470, -0.6226],
                      ...,
                      [ 1.6393,  0.6826, -0.4277,  ..., -2.2997, -0.9771, -0.2916],
                      [-1.5357,  1.8551,  0.5394,  ..., -0.6225, -1.0055, -0.3962],
                      [-0.2480,  1.7671, -0.8074,  ..., -3.1909, -0.4274, -0.5168]])),
             ('position_embedding.weight',
              tensor([[-1.0003e-31,  9.4428e-32,  1.0142e-31,  ...,  1.0253e-31,
                        9.8931e-32, -1.0783e-31],
                      [ 1.0460e-31,  9.9900e-32,  9.4717e-32,  ...,  1.0345e-31,
                       -9.7955e-32, -9.9962e-32],
                      [-1.0135e-31, -1.0074e-31,  1.0369e-31,  ..., -1.0177e-31,
                        1.0016e-31,  9.72

In [ ]:
user_id_to_index[487], item_id_to_index[6], item_index_to_id[1]

(3, 2, 5)

In [215]:
model.state_dict()

OrderedDict([('item_embedding.weight',
              tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
                      [-1.7795,  0.0642,  0.0860,  ...,  1.1958,  0.6133,  0.1600],
                      [ 1.5584,  0.0131, -0.8033,  ..., -0.3310, -0.9356, -0.6179],
                      ...,
                      [ 1.4869,  0.6814, -0.2091,  ..., -2.2190, -1.2260, -0.2538],
                      [-1.2911,  1.9992,  0.4574,  ..., -0.7450, -1.0046, -0.7227],
                      [-0.3827,  1.5944, -0.7970,  ..., -3.2430, -0.5140, -0.5547]])),
             ('position_embedding.weight',
              tensor([[-1.0003e-31,  9.4428e-32,  1.0142e-31,  ...,  1.0253e-31,
                        9.8931e-32, -1.0783e-31],
                      [ 1.0460e-31,  9.9900e-32,  9.4717e-32,  ...,  1.0345e-31,
                       -9.7955e-32, -9.9962e-32],
                      [-1.0135e-31, -1.0074e-31,  1.0369e-31,  ..., -1.0177e-31,
                        1.0016e-31,  9.72